-- ======================================================
-- SCRIPT DE CRIAÇÃO DAS TABELAS (H2)
-- Sistema de Gestão de Infraestruturas e Incidentes (ITSM)
-- ======================================================

-- Tabela de utilizadores
CREATE TABLE IF NOT EXISTS utilizador (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

-- Tabela de técnicos (herança simples)
CREATE TABLE IF NOT EXISTS tecnico (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       utilizador_id BIGINT NOT NULL UNIQUE,
                                       disponibilidade VARCHAR(2000),  -- JSON armazenado como string
    carga_trabalho_atual INT DEFAULT 0,
    FOREIGN KEY (utilizador_id) REFERENCES utilizador(id) ON DELETE CASCADE
    );

-- Tabela de competências
CREATE TABLE IF NOT EXISTS competencia (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           nome VARCHAR(50) NOT NULL UNIQUE
    );

-- Tabela de associação N:N entre técnicos e competências
CREATE TABLE IF NOT EXISTS tecnico_competencia (
                                                   tecnico_id BIGINT NOT NULL,
                                                   competencia_id BIGINT NOT NULL,
                                                   PRIMARY KEY (tecnico_id, competencia_id),
    FOREIGN KEY (tecnico_id) REFERENCES tecnico(id) ON DELETE CASCADE,
    FOREIGN KEY (competencia_id) REFERENCES competencia(id) ON DELETE CASCADE
    );

-- Tabela de ativos (hardware/software)
CREATE TABLE IF NOT EXISTS ativo (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     tipo VARCHAR(50) NOT NULL,
    nome VARCHAR(100) NOT NULL,
    estado VARCHAR(30) NOT NULL,
    data_aquisicao DATE,
    especificacoes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

-- Tabela de tickets (incidentes/pedidos)
CREATE TABLE IF NOT EXISTS ticket (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      titulo VARCHAR(100) NOT NULL,
    descricao TEXT NOT NULL,
    prioridade VARCHAR(20) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    estado VARCHAR(30) NOT NULL,
    data_abertura TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_fecho TIMESTAMP,
    tecnico_id BIGINT,
    aberto_por_id BIGINT NOT NULL,
    ativo_id BIGINT,
    FOREIGN KEY (tecnico_id) REFERENCES tecnico(id) ON DELETE SET NULL,
    FOREIGN KEY (aberto_por_id) REFERENCES utilizador(id),
    FOREIGN KEY (ativo_id) REFERENCES ativo(id) ON DELETE SET NULL
    );

-- Tabela de comentários nos tickets
CREATE TABLE IF NOT EXISTS comentario (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          texto TEXT NOT NULL,
                                          data_hora TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                          ticket_id BIGINT NOT NULL,
                                          tecnico_id BIGINT NOT NULL,
                                          FOREIGN KEY (ticket_id) REFERENCES ticket(id) ON DELETE CASCADE,
    FOREIGN KEY (tecnico_id) REFERENCES tecnico(id)
    );

-- ======================================================
-- ÍNDICES PARA MELHOR PERFORMANCE
-- ======================================================
CREATE INDEX IF NOT EXISTS idx_ticket_estado ON ticket(estado);
CREATE INDEX IF NOT EXISTS idx_ticket_tecnico ON ticket(tecnico_id);
CREATE INDEX IF NOT EXISTS idx_ticket_data_abertura ON ticket(data_abertura);
CREATE INDEX IF NOT EXISTS idx_tecnico_carga ON tecnico(carga_trabalho_atual);
CREATE INDEX IF NOT EXISTS idx_utilizador_role ON utilizador(role);